### ISSUE TITLE
Error in sml2emeter.ino

### ISSUE THREAD

**Issue by s0170071** [jtuemmler/sml2emeter#3]
The following code causes a WDT reset.

```
void readTestPacket() {
   Serial.print("W");
   ledOff();
   delayMs(1000 - TEST_PACKET_RECEIVE_TIME_MS);
   Serial.print("R");
   ledOn();
   delay(TEST_PACKET_RECEIVE_TIME_MS);
   smlStreamReader.addData(SML_TEST_PACKET, SML_TEST_PACKET_LENGTH);
   ledOff();
}
```

A fix is to replace the second delay with delayMs.

**Comment by jtuemmler** [comment]
Thanks. The method has been updated. I'm not using the readTestPacket method any more, because there is now a python-script to emulate a sml meter.
