### ISSUE TITLE
CRC check reads OK if no data is in the packet. 

### ISSUE THREAD

**Issue by s0170071** [jtuemmler/sml2emeter#5]
The `bool parsePacket(const uint8_t *pPacket, int packetLength) {` function does not check wether the packetLength parameter is 0.  If an empty packet is passed (i.e. no serial connection ), the CRC is reported as okay. 
packetLength needs to be larger than 10 or so.

**Comment by jtuemmler** [comment]
Thanks. Code has been updated in the meantime (together with changes for issue #6 ).
