### ISSUE TITLE
cannot find WifiUdp.h on linux

### ISSUE THREAD

**Issue by s0170071** [jtuemmler/sml2emeter#7]
fix: 
in sml2emeter.ino change the include statement from 

#include <WiFiUDP.h>

to 
#include "util/WiFiUDP.h"

**Comment by jtuemmler** [comment]
WiFiUDP.h is just a small compatibilty library to be able to compile the original Arduino sketch on linux/windows without the Arduino IDE. The cmake-configuration file is adding the util directory to the include path. Therefore the include works this way from the Arduino IDE and also when using any other c++ compiler.
